-- Live Finals confirmation system for MEZZOPEDIA 2026
-- Run this once in the Supabase SQL Editor connected to the Mezzopedia Registration portal.
-- It creates a dedicated finalist confirmation table, secure RPCs, an audit log,
-- and seeds the final 53 contestants from the approved live-finals list.

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create table if not exists public.live_finalists (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  unique_code text not null unique,
  class_name text not null,
  school_name text,
  school_location text,
  region text,
  email text,
  phone text,
  whatsapp text,
  travel_from text,
  companion_name text,
  companion_relationship text,
  companion_phone text,
  reporting_date date not null,
  confirmation_status text not null default 'pending'
    check (confirmation_status in ('pending', 'confirmed')),
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists live_finalists_name_trgm_idx
  on public.live_finalists using gin (full_name gin_trgm_ops);
create index if not exists live_finalists_reporting_date_idx
  on public.live_finalists (reporting_date);
create index if not exists live_finalists_confirmation_status_idx
  on public.live_finalists (confirmation_status);
create index if not exists live_finalists_region_idx
  on public.live_finalists (region);
create index if not exists live_finalists_class_idx
  on public.live_finalists (class_name);

create table if not exists public.live_finalist_confirmation_log (
  id bigint generated by default as identity primary key,
  finalist_id uuid not null references public.live_finalists(id) on delete cascade,
  action text not null default 'confirm',
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_live_finalist_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_live_finalists_updated_at on public.live_finalists;
create trigger set_live_finalists_updated_at
before update on public.live_finalists
for each row execute function public.set_live_finalist_updated_at();

alter table public.live_finalists enable row level security;
alter table public.live_finalist_confirmation_log enable row level security;

-- No direct public table access is required. Public users search and confirm through
-- the two SECURITY DEFINER functions below, which prevents anonymous bulk editing.
drop policy if exists "No direct public finalist access" on public.live_finalists;
drop policy if exists "No direct public finalist log access" on public.live_finalist_confirmation_log;

create or replace function public.search_live_finalists(p_query text)
returns table (
  id uuid,
  full_name text,
  class_name text,
  school_name text,
  school_location text,
  region text,
  email text,
  phone text,
  whatsapp text,
  travel_from text,
  companion_name text,
  companion_relationship text,
  companion_phone text,
  reporting_date date,
  confirmation_status text,
  confirmed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    lf.id, lf.full_name, lf.class_name, lf.school_name, lf.school_location, lf.region,
    lf.email, lf.phone, lf.whatsapp, lf.travel_from, lf.companion_name,
    lf.companion_relationship, lf.companion_phone, lf.reporting_date,
    lf.confirmation_status, lf.confirmed_at
  from public.live_finalists lf
  where length(trim(coalesce(p_query, ''))) >= 2
    and lf.full_name ilike '%' || trim(p_query) || '%'
  order by lf.full_name
  limit 25;
$$;

create or replace function public.confirm_live_finalist(
  p_id uuid,
  p_unique_code text,
  p_school_name text,
  p_school_location text,
  p_region text,
  p_email text,
  p_phone text,
  p_whatsapp text,
  p_travel_from text,
  p_companion_name text,
  p_companion_relationship text,
  p_companion_phone text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  expected_code text;
  updated_row public.live_finalists;
begin
  select unique_code into expected_code
  from public.live_finalists
  where id = p_id;

  if expected_code is null then
    raise exception 'Finalist record not found.';
  end if;

  if upper(trim(coalesce(p_unique_code, ''))) <> upper(trim(expected_code)) then
    raise exception 'The user code is incorrect. Please check your contest user code and try again.';
  end if;

  update public.live_finalists
  set
    school_name = nullif(trim(coalesce(p_school_name, '')), ''),
    school_location = nullif(trim(coalesce(p_school_location, '')), ''),
    region = nullif(trim(coalesce(p_region, '')), ''),
    email = nullif(trim(coalesce(p_email, '')), ''),
    phone = nullif(trim(coalesce(p_phone, '')), ''),
    whatsapp = nullif(trim(coalesce(p_whatsapp, '')), ''),
    travel_from = nullif(trim(coalesce(p_travel_from, '')), ''),
    companion_name = nullif(trim(coalesce(p_companion_name, '')), ''),
    companion_relationship = nullif(trim(coalesce(p_companion_relationship, '')), ''),
    companion_phone = nullif(trim(coalesce(p_companion_phone, '')), ''),
    confirmation_status = 'confirmed',
    confirmed_at = now()
  where id = p_id
  returning * into updated_row;

  insert into public.live_finalist_confirmation_log (finalist_id, action, snapshot)
  values (
    p_id,
    'confirm',
    jsonb_build_object(
      'full_name', updated_row.full_name,
      'class_name', updated_row.class_name,
      'school_name', updated_row.school_name,
      'school_location', updated_row.school_location,
      'region', updated_row.region,
      'email', updated_row.email,
      'phone', updated_row.phone,
      'whatsapp', updated_row.whatsapp,
      'travel_from', updated_row.travel_from,
      'companion_name', updated_row.companion_name,
      'companion_relationship', updated_row.companion_relationship,
      'companion_phone', updated_row.companion_phone,
      'reporting_date', updated_row.reporting_date,
      'confirmed_at', updated_row.confirmed_at
    )
  );

  return true;
end;
$$;

revoke all on function public.search_live_finalists(text) from public;
revoke all on function public.confirm_live_finalist(uuid,text,text,text,text,text,text,text,text,text,text,text) from public;
grant execute on function public.search_live_finalists(text) to anon, authenticated;
grant execute on function public.confirm_live_finalist(uuid,text,text,text,text,text,text,text,text,text,text,text) to anon, authenticated;

insert into public.live_finalists (
  full_name, unique_code, class_name, school_name, school_location, region,
  email, phone, whatsapp, travel_from, companion_name, companion_relationship,
  companion_phone, reporting_date
)
values
  ('Albert Chris Essel Donkoh', 'MNMCA0002', 'Adults', null, 'Mankessim', 'Central Region', 'dprincipal90@gmail.com', '0530651855', null, 'Mankessim', null, null, null, '2026-09-02'),
  ('Emmanuel Arku Korsah', 'MNMCA0005', 'Adults', null, 'Tema, Golf City', 'Greater Accra Region', 'korsah578@gmail.com', '0506936923', null, 'Tema, Golf City', null, null, null, '2026-09-02'),
  ('Frimpong Nana Akowuah', 'MNMCA0006', 'Adults', null, 'Atonsu', 'Ashanti Region', 'akowuahnana00@gmail.com', '0593460494', null, 'Atonsu', null, null, null, '2026-09-02'),
  ('Godwin Kwaku Dornyo', 'MNMCA0036', 'Adults', null, 'Agbozume', 'Volta Region', 'godwindornyo13@gmail.com', '0545161071', null, 'Agbozume', null, null, null, '2026-09-02'),
  ('Solomon Affum', 'MNMCA0035', 'Adults', null, 'Asamankese', 'Eastern Region', 'solomonaffum85@gmail.com', '0242101896', null, 'Asamankese', null, null, null, '2026-09-02'),
  ('Atuahene Kezia', 'MNMC00160', 'JHS 1', 'Leesbon Educational Centre', 'Asokore Mampong, Kumasi, P.O, AN 2914', 'Ashanti Region', 'yawagyenimboateng90@gmail.com', '0242819324', null, 'Asokore Mampong, Kumasi, P.O, AN 2914', 'Joyce Ackah', 'Guardian', '0242819324', '2026-09-01'),
  ('Hilton Scott Ebbah', 'MNMC00102', 'JHS 1', 'Republic Academy', 'Obom Road, Kasoa', 'Central Region', 'michaelfosu5080@gmail.com', '+233555111979', null, 'Obom Road, Kasoa', 'Mrs Anita Ahiabu', 'Guardian', '0555111979', '2026-09-01'),
  ('Jeremy Mawuena Hodonu', 'MNMC00103', 'JHS 1', 'Republic Academy', 'Obom Road, Kasoa', 'Central Region', 'enninrita2024@gmail.com', '+233242031383', null, 'Obom Road, Kasoa', 'Ophelia Addai Hodonu', 'Guardian', '0242031383', '2026-09-01'),
  ('Kobea Joseph Godson', 'MNMC00035', 'JHS 1', null, null, null, 'mavisadjei112233@gmail.com', '+233593312311', null, null, null, null, null, '2026-09-01'),
  ('Mohammed Abdul-Faheem Borenyi', 'MNMC00168', 'JHS 1', 'SDA JHS B', 'Buipe-Bridge', 'Savannah Region', 'kamilajob234@gmail.com', '0208074933', null, 'Buipe-Bridge', 'Mohammed Kamila Job', 'Guardian', '0208074933', '2026-09-01'),
  ('Mozimbil Selina', 'MNMC00159', 'JHS 1', 'Leesbon Educational Centre', 'Asokore Mampong, Kumasi, P.O, Box 2419', 'Ashanti Region', 'yawagyenimboateng90@gmail.com', '0243707965', null, 'Asokore Mampong, Kumasi, P.O, Box 2419', 'Nang Elizabeth', 'Guardian', '0243707965', '2026-09-01'),
  ('Quinnella Adwoa Adutwumwah Darko', 'MNMC00099', 'JHS 1', 'Republic Academy', 'Obom Road, Kasoa', 'Central Region', 'elizabethekoh97@gmail.com', '+233244929997', null, 'Obom Road, Kasoa', 'Elizabeth Ekoh', 'Guardian', '0244929997', '2026-09-01'),
  ('Yayra Enam Ankora', 'MNMC00129', 'JHS 1', 'United Church School', 'TESHIE-NUNGUA', 'Greater Accra Region', 'rolanddadzoe@gmail.com', '0244990103', null, 'TESHIE-NUNGUA', 'Grace Worlanyo Krah', 'Guardian', '0244990103', '2026-09-01'),
  ('Abdul Mateen Hafiz', 'MNMC00161', 'JHS 2', 'Leesbon Educational Centre', 'Asokore Mampong, Kumasi, P.O, Box AN 2914', 'Ashanti Region', 'yawagyenimboateng90@gmail.com', '0556563000', null, 'Asokore Mampong, Kumasi, P.O, Box AN 2914', 'Hajia Zeena Salifu', 'Guardian', '0556563000', '2026-09-01'),
  ('Adebiyi Precious Abena Adenike Adom', 'MNMC00107', 'JHS 2', 'Perseverance International School', 'Nsawam', 'Greater Accra Region', 'adebiyialice26@gmail.com', '+233243368919', null, 'Nsawam', 'Alice N-yellabong', 'Guardian', '0243368919', '2026-09-01'),
  ('Dinah Naadu Ayertey', 'MNMC00148', 'JHS 2', 'United Church School', 'TESHIE-NUNGUA', 'Greater Accra Region', 'rolanddadzoe@gmail.com', '0246277100', null, 'TESHIE-NUNGUA', 'Vida Dornor Pewudie', 'Guardian', '+233246277100', '2026-09-01'),
  ('Haatim Adam', 'MNMC00028', 'JHS 2', 'Gold Avenue', 'Old Ashongman', 'Greater Accra Region', 'haatim201411@gmail.com', '+233244187975', null, 'Old Ashongman', 'Mr. Nurudeen Adam', 'Guardian', '0244187975', '2026-09-01'),
  ('Jersey Darko Owusu', 'MNMC00005', 'JHS 2', 'Mirekua International Community School', 'Sapeiman - Accra', 'Greater Accra Region', 'ladyjulia1990@gmail.com', '+233547579996', null, 'Sapeiman - Accra', 'Juliana Nyarkoah Ababio', 'Guardian', '0547579996', '2026-09-01'),
  ('Akosua Nyamekye Oforiwa Akonnor', 'MNMC00079', 'JHS 3', 'Mart Beck International School', 'Kasoa Papaase No. 2', 'Central Region', 'kwabs24@gmail.com', '+233249482839', null, 'Kasoa Papaase No. 2', 'Sampson Boamah', 'Guardian', '0249482839', '2026-09-01'),
  ('Angela Yayra Anyomi', 'MNMC00126', 'JHS 3', 'Dar-Es-Salaam JHS', 'TESHIE-NUNGUA', 'Greater Accra Region', 'rolanddadzoe@gmail.com', '0243954615', null, 'TESHIE-NUNGUA', 'Daniel Anyomi', 'Guardian', '0243954615', '2026-09-01'),
  ('Barima Okyere Ofori Ayim', 'MNMC00062', 'JHS 3', 'Presbyterian Preparatory School', 'Nii Boi Town', 'Greater Accra Region', 'fletcherszoe@gmail.com', '+233555071570', null, 'Nii Boi Town', 'Essel Dorothy', 'Guardian', '0555071570', '2026-09-01'),
  ('Boadi appah Earl Jason', 'MNMC00060', 'JHS 3', 'Accra high school', 'North ridge', 'Greater Accra Region', 'earlboadi8@gmail.com', '+233508787500', null, 'North ridge', 'Mrs. Dorcas Dankwa', 'Guardian', '0508787500', '2026-09-01'),
  ('Fidèlle Sena Dzivenu', 'MNMC00049', 'JHS 3', 'Kotobabi ''3'' Basic school', 'Kotobabi', 'Greater Accra Region', 'thepinkhood11@gmail.com', '+233553847919', null, 'Kotobabi', 'Delali Togbe', 'Guardian', '0553847919', '2026-09-01'),
  ('Hakeem Botchwey', 'MNMC00075', 'JHS 3', 'Mart Beck International School', 'Kasoa Papaase', 'Central Region', 'kwabs24@gmail.com', '+233249482839', null, 'Kasoa Papaase', 'Sampson Boamah', 'Guardian', '0249482839', '2026-09-01'),
  ('Joshua Edem Dotse', 'MNMC00078', 'JHS 3', 'Mart Beck International School', 'Kasoa Papaase No. 2', 'Central Region', 'kwabs24@gmail.com', '+233249482839', null, 'Kasoa Papaase No. 2', 'Sampson Boamah', 'Guardian', '0249482839', '2026-09-01'),
  ('Nana Yaw Peprah', 'MNMC00089', 'JHS 3', 'ROKA INTERNATIONAL SCHOOL', 'FISE-ACCRA', 'Greater Accra Region', 'jamespeprahboateng57@gmail.com', '+233554615538', null, 'FISE-ACCRA', 'Thelma Klewiah', 'Guardian', '0554615538', '2026-09-01'),
  ('Prudence Mensah', 'MNMC00125', 'JHS 3', 'United Church School', 'TESHIE-NUNGUA', 'Greater Accra Region', 'rolanddadzoe@gmail.com', '0243452977', null, 'TESHIE-NUNGUA', 'Alfred Mensah', 'Guardian', '0243452977', '2026-09-01'),
  ('ADELAYITA SHEENA DZIEDZORM', 'MNMC00180', 'Primary 5', 'Crystal Height International School', 'Shikpontele, Amasaman', 'Greater Accra Region', 'roselklut@gmail.com', '0249594954', '0249594954', 'Shikpontele, Amasaman', 'KLUTSE-ADELAYITA ROSE ELORM', 'Guardian', '0249594954', '2026-08-31'),
  ('Alisha Zaynab Belem', 'MNMC00150', 'Primary 5', 'Linvoy Academy', 'Kpobiman-Container', 'Greater Accra Region', 'enninrita2024@gmail.com', '0204163245', null, 'Kpobiman-Container', 'Adama Belem', 'Guardian', '0204163245', '2026-08-31'),
  ('Dagbe Awushie Wagba', 'MNMC00145', 'Primary 5', 'United Church School', 'TESHIE-NUNGUA', 'Greater Accra Region', 'rolanddadzoe@gmail.com', '0591899847', null, 'TESHIE-NUNGUA', 'Wisdom Worlanyo Wagba', 'Guardian', '0591899847', '2026-08-31'),
  ('Grace Wilhelmina Yaa Kekeli Deku', 'MNMC00117', 'Primary 5', 'PETHELEN MONTESSORI', 'TIAFA', 'Greater Accra Region', 'lynagold80@gmail.com', '+233244679807', null, 'TIAFA', 'Christopher Deku', 'Guardian', '0244679807', '2026-08-31'),
  ('Nana Kwesi Ansah Tyrell Elvin Enzo', 'MNMC00144', 'Primary 5', 'Bridge Roses Montessori', 'Ashongman Estate, Accra', 'Greater Accra Region', 'ewuakyeadjeib@gmail.com', '0245738998', null, 'Ashongman Estate, Accra', 'Celestine Adjei', 'Guardian', '0245738998', '2026-08-31'),
  ('Bediako Grace', 'MNMC00169', 'Primary 6', 'Leesbon Educational Centre', 'Asokore Mampong, Ashanti, Region', 'Ashanti Region', 'yawagyenimboateng90@gmail.com', '0249934037', '0550927668', 'Asokore Mampong, Ashanti, Region', 'Naana Juliana Attia', 'Guardian', '0249934037', '2026-08-31'),
  ('Dakora McKinley', 'MNMC00112', 'Primary 6', 'King Solomon International School', 'Nkontwima, New Road', 'Ashanti Region', 'koaj334@gmail.com', '+233593312311', null, 'Nkontwima, New Road', 'Sir Amaniampong Ofosuhene Kwaku', 'Guardian', '0593312311', '2026-08-31'),
  ('Daniel Amenyo Abiwu', 'MNMC00177', 'Primary 6', 'Morning Angels Basic School', 'Dome', 'Greater Accra Region', 'gademordavid23@gmail.com', '0544168690', '0544168690', 'Dome', 'Confidence Abiwu', 'Guardian', '0544168690', '2026-08-31'),
  ('Danielle Abla Dugbenu', 'MNMC00088', 'Primary 6', 'Crystal Height International School', 'Amasaman, Shikpontele', 'Greater Accra Region', 'kojodumas@gmail.com', '+233242312640', null, 'Amasaman, Shikpontele', 'Lawrenda Pappoe', 'Guardian', '0242312640', '2026-08-31'),
  ('DESMOND MENSAH', 'MNMC00022', 'Primary 6', 'His Majesty School, Mankessim', 'Mankessim', 'Central Region', 'dprincipal90@gmail.com', '+233593272535', null, 'Mankessim', 'BENEDICT BUABENG', 'Guardian', '+233593272535', '2026-08-31'),
  ('Gad Kobina Yeboah', 'MNMC00175', 'Primary 6', 'His Majesty School, Mankessim', 'Mankessim', 'Central Region', 'dprincipal90@gmail.com', '0596865190', '0596865190', 'Mankessim', 'Mr. Albert Chris Essel Donkoh', 'Guardian', '0596865190', '2026-08-31'),
  ('Jadon Novignon', 'MNMC00119', 'Primary 6', 'Crystal Heights International School', 'Amasaman', 'Greater Accra Region', 'jnovignon2015@gmail.com', '+233599523813', null, 'Amasaman', 'Augustina Novignon', 'Guardian', '0599523813', '2026-08-31'),
  ('Joel Bortei Boye Doku', 'MNMC00149', 'Primary 6', 'United Church School', 'TESHIE-NUNGUA', 'Greater Accra Region', 'rolanddadzoe@gmail.com', '0264888863', null, 'TESHIE-NUNGUA', 'Benjamin Boye Doku', 'Guardian', '0264888863', '2026-08-31'),
  ('Kelvin Asamoah', 'MNMC00171', 'Primary 6', 'Leesbon Educational Centre', 'Asokore Mampong', 'Ashanti Region', 'yawagyenimboateng90@gmail.com', '0545348284', '0550927668', 'Asokore Mampong', 'Fauzia Awuah', 'Guardian', '0545348284', '2026-08-31'),
  ('Madiba Oduro Acheampong', 'MNMC00059', 'Primary 6', 'King Solomon International School', 'New Road, Nkontwima', 'Ashanti Region', 'koaj334@gmail.com', '+233547699755', null, 'New Road, Nkontwima', 'Mavis Agyei', 'Guardian', '+233547699755', '2026-08-31'),
  ('Michelle Ama Serwaa Ayim', 'MNMC00042', 'Primary 6', 'Crystal Heights International School', 'Accra - Amasaman', 'Greater Accra Region', 'eayim6011@gmail.com', '0244303313', '+233 59 299 9299', 'Accra - Amasaman', 'Evans K. Ayim', 'Guardian', '0244303313', '2026-08-31'),
  ('Muhammad Awal lbrahim', 'MNMC00170', 'Primary 6', 'Leesbon Educational Centre', 'Asokore Mampong, Ashanti, Region', 'Ashanti Region', 'yawagyenimboateng90@gmail.com', '0246136448', '0550927668', 'Asokore Mampong, Ashanti, Region', 'Hummu Suleiman', 'Guardian', '0246136448', '2026-08-31'),
  ('Nazarena A. Kwao', 'MNMC00085', 'Primary 6', 'Crystal Heights International School', 'Amasaman', 'Greater Accra Region', 'jay.efya.den@gmail.com', '+233242515048', null, 'Amasaman', 'Jennifer Denkyi', 'Guardian', '0242515048', '2026-08-31'),
  ('Paul Etornam Doe', 'MNMC00032', 'Primary 6', 'Crystals Heights International School', 'Sapeiman', 'Greater Accra Region', 'voicetomen@gmail.com', '+233249167853', null, 'Sapeiman', 'Dorcas Doe', 'Guardian', '0249167853', '2026-08-31'),
  ('Sedinam Dei', 'MNMC00072', 'Primary 6', 'Services Primary and Junior High School', 'Burma Camp', 'Greater Accra Region', 'patiencedei12@gmail.com', '+233244622432', null, 'Burma Camp', 'Patience Gomashie Dei', 'Guardian', '0244622432', '2026-08-31'),
  ('Theikos Ofori', 'MNMC00004', 'Primary 6', 'Sincere Care Montessori School', 'Broadcasting, Weija, off, Accra-Cape Coast Highway', 'Greater Accra Region', 'georgeofori83@gmail.com', '+233244633609', null, 'Broadcasting, Weija, off, Accra-Cape Coast Highway', 'George Ofori', 'Guardian', '0244633609', '2026-08-31'),
  ('Amegah-Awli Edwin Dziedzorm', 'MNMC00073', 'SHS', 'Presbyterian Boys'' Secondary School', 'East Legon', 'Greater Accra Region', 'amegahawlidziedzorm@gmail.com', '+233242911547', null, 'East Legon', 'Komla Awli', 'Guardian', '0242911547', '2026-09-02'),
  ('George Lordson Dadzie', 'MNMCA0032', 'SHS', null, 'Takoradi', 'Western Region', 'dadziegeorgelordson@gmail.com', '0206116609', null, 'Takoradi', null, null, null, '2026-09-02'),
  ('Mensah Addai Michael', 'MNMCA0030', 'SHS', null, 'Kumasi', 'Ashanti Region', 'teslamichael22@gmail.com', '0533308763', null, 'Kumasi', null, null, null, '2026-09-02'),
  ('Nzebah Michael', 'MNMC00121', 'SHS', 'St. Thomas Senior High Technical School', 'Asamankese', 'Greater Accra Region', 'nzebahmichael@gmail.com', '0548768752', null, 'Asamankese', 'Nzebah Gabriel', 'Guardian', '0548768752', '2026-09-02'),
  ('YELOUH AGODOE JOYCE', 'MNMC00038', 'SHS', 'ECOLE RONSARD', 'EAST LEGON', 'Greater Accra Region', 'joyceyelouh@gmail.com', '+233545008731', null, 'EAST LEGON', 'ROSE XOLASSE TOKPAH', 'Guardian', '0545008731', '2026-09-02')
on conflict (unique_code) do update
set
  full_name = excluded.full_name,
  class_name = excluded.class_name,
  school_name = excluded.school_name,
  school_location = excluded.school_location,
  region = excluded.region,
  email = excluded.email,
  phone = excluded.phone,
  whatsapp = excluded.whatsapp,
  travel_from = excluded.travel_from,
  companion_name = excluded.companion_name,
  companion_relationship = excluded.companion_relationship,
  companion_phone = excluded.companion_phone,
  reporting_date = excluded.reporting_date,
  updated_at = now()
where public.live_finalists.confirmation_status = 'pending';

-- Quick verification
select
  count(*) as finalists,
  count(*) filter (where confirmation_status = 'confirmed') as confirmed,
  count(*) filter (where confirmation_status = 'pending') as pending
from public.live_finalists;
